/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <Foundation/NSString.h>

@interface NSString (UIStringDrawingDeprecated)
- (void)drawAtPoint:(struct CGPoint)fp8 withStyle:(id)fp16;
- (void)drawInRect:(struct CGRect)fp8 withStyle:(id)fp24;
- (void)drawMarkupAtPoint:(struct CGPoint)fp8;
- (void)drawMarkupInRect:(struct CGRect)fp8;
- (struct CGSize)sizeWithStyle:(id)fp8 forWidth:(float)fp12;
- (struct CGSize)sizeWithMarkupForWidth:(float)fp8;
- (void)setStringDrawingOrigin:(struct CGPoint)fp8;
- (void)clearStringDrawingOrigin;
- (struct CGSize)sizeWithFont:(id)fp8;
- (struct CGSize)sizeWithFont:(id)fp8 forWidth:(float)fp12 ellipsis:(int)fp16;
- (struct CGSize)drawAtPoint:(struct CGPoint)fp8 forWidth:(float)fp16 withFont:(id)fp20 ellipsis:(int)fp24;
- (struct CGSize)sizeWithFont:(id)fp8 minFontSize:(float)fp12 actualFontSize:(float *)fp16 forWidth:(float)fp20 ellipsis:(int)fp24;
- (struct CGSize)drawAtPoint:(struct CGPoint)fp8 forWidth:(float)fp16 withFont:(id)fp20 fontSize:(float)fp24 ellipsis:(int)fp28 baselineAdjustment:(int)fp32;
- (struct CGSize)drawAtPoint:(struct CGPoint)fp8 forWidth:(float)fp16 withFont:(id)fp20 minFontSize:(float)fp24 actualFontSize:(float *)fp28 ellipsis:(int)fp32 baselineAdjustment:(int)fp36;
- (struct CGSize)drawInRect:(struct CGRect)fp8 withFont:(id)fp24 ellipsis:(int)fp28;
- (struct CGSize)drawInRect:(struct CGRect)fp8 withFont:(id)fp24 ellipsis:(int)fp28 alignment:(int)fp32;
- (struct CGSize)drawInRect:(struct CGRect)fp8 withFont:(id)fp24;
- (struct CGSize)sizeInRect:(struct CGRect)fp8 withFont:(id)fp24 ellipsis:(int)fp28;
- (struct CGSize)sizeInRect:(struct CGRect)fp8 withFont:(id)fp24;
@end

